/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscribersRouteImport } from './routes/_authenticated/subscribers'
import { Route as ApiPublicCronScrapeRouteImport } from './routes/api/public/cron/scrape'
import { Route as ApiPublicRJobIdRouteImport } from './routes/api/public/r/$jobId'
import { Route as ApiPublicTelegramPremiumWebhookRouteImport } from './routes/api/public/telegram-premium/webhook'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramBotsBotIdWebhookRouteImport } from './routes/api/public/telegram-bots/$botId/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscribersRoute =
  AuthenticatedSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronScrapeRoute = ApiPublicCronScrapeRouteImport.update({
  id: '/api/public/cron/scrape',
  path: '/api/public/cron/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRJobIdRoute = ApiPublicRJobIdRouteImport.update({
  id: '/api/public/r/$jobId',
  path: '/api/public/r/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramPremiumWebhookRoute =
  ApiPublicTelegramPremiumWebhookRouteImport.update({
    id: '/api/public/telegram-premium/webhook',
    path: '/api/public/telegram-premium/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramBotsBotIdWebhookRoute =
  ApiPublicTelegramBotsBotIdWebhookRouteImport.update({
    id: '/api/public/telegram-bots/$botId/webhook',
    path: '/api/public/telegram-bots/$botId/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
  '/api/public/r/$jobId': typeof ApiPublicRJobIdRoute
  '/api/public/telegram-premium/webhook': typeof ApiPublicTelegramPremiumWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram-bots/$botId/webhook': typeof ApiPublicTelegramBotsBotIdWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscribers': typeof AuthenticatedSubscribersRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
  '/api/public/r/$jobId': typeof ApiPublicRJobIdRoute
  '/api/public/telegram-premium/webhook': typeof ApiPublicTelegramPremiumWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram-bots/$botId/webhook': typeof ApiPublicTelegramBotsBotIdWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bots': typeof AuthenticatedBotsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscribers': typeof AuthenticatedSubscribersRoute
  '/api/public/cron/scrape': typeof ApiPublicCronScrapeRoute
  '/api/public/r/$jobId': typeof ApiPublicRJobIdRoute
  '/api/public/telegram-premium/webhook': typeof ApiPublicTelegramPremiumWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telegram-bots/$botId/webhook': typeof ApiPublicTelegramBotsBotIdWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/bots'
    | '/dashboard'
    | '/jobs'
    | '/keywords'
    | '/settings'
    | '/subscribers'
    | '/api/public/cron/scrape'
    | '/api/public/r/$jobId'
    | '/api/public/telegram-premium/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram-bots/$botId/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/bots'
    | '/dashboard'
    | '/jobs'
    | '/keywords'
    | '/settings'
    | '/subscribers'
    | '/api/public/cron/scrape'
    | '/api/public/r/$jobId'
    | '/api/public/telegram-premium/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram-bots/$botId/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/bots'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/keywords'
    | '/_authenticated/settings'
    | '/_authenticated/subscribers'
    | '/api/public/cron/scrape'
    | '/api/public/r/$jobId'
    | '/api/public/telegram-premium/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/telegram-bots/$botId/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronScrapeRoute: typeof ApiPublicCronScrapeRoute
  ApiPublicRJobIdRoute: typeof ApiPublicRJobIdRoute
  ApiPublicTelegramPremiumWebhookRoute: typeof ApiPublicTelegramPremiumWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelegramBotsBotIdWebhookRoute: typeof ApiPublicTelegramBotsBotIdWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscribers': {
      id: '/_authenticated/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AuthenticatedSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/scrape': {
      id: '/api/public/cron/scrape'
      path: '/api/public/cron/scrape'
      fullPath: '/api/public/cron/scrape'
      preLoaderRoute: typeof ApiPublicCronScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$jobId': {
      id: '/api/public/r/$jobId'
      path: '/api/public/r/$jobId'
      fullPath: '/api/public/r/$jobId'
      preLoaderRoute: typeof ApiPublicRJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-premium/webhook': {
      id: '/api/public/telegram-premium/webhook'
      path: '/api/public/telegram-premium/webhook'
      fullPath: '/api/public/telegram-premium/webhook'
      preLoaderRoute: typeof ApiPublicTelegramPremiumWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-bots/$botId/webhook': {
      id: '/api/public/telegram-bots/$botId/webhook'
      path: '/api/public/telegram-bots/$botId/webhook'
      fullPath: '/api/public/telegram-bots/$botId/webhook'
      preLoaderRoute: typeof ApiPublicTelegramBotsBotIdWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscribersRoute: typeof AuthenticatedSubscribersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBotsRoute: AuthenticatedBotsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscribersRoute: AuthenticatedSubscribersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronScrapeRoute: ApiPublicCronScrapeRoute,
  ApiPublicRJobIdRoute: ApiPublicRJobIdRoute,
  ApiPublicTelegramPremiumWebhookRoute: ApiPublicTelegramPremiumWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelegramBotsBotIdWebhookRoute:
    ApiPublicTelegramBotsBotIdWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
